// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqzuvqwsaeguphqjwvap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xenV2cXdzYWVndXBocWp3dmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTkwMzgsImV4cCI6MjA2NTU5NTAzOH0.NjN6dcoIXfmGkbwle0_EeKziDysY5RSkTNZzz9LpwIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);